language: c
compiler: gcc
before_script:
    - sudo apt-get install -qq build-essential gnome-common libgtk-3-dev libenchant-dev gtk-doc-tools libvala-dev gobject-introspection
script: 
    - ./autogen.sh
    - ./configure --enable-gtk-doc
    - make V=1
